language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - wget https://hg.python.org/cpython/archive/default.tar.bz2
  - tar -xf default.tar.bz2
  - cd cpython-*
  - ./configure --prefix=$HOME/.local/
  - make -j 2
  - make install
  - cd ..
  - ~/.local/bin/python3 -m compileall -b pythonlib examples
script:
  - cargo test
  - ~/.local/bin/python3 run_functional_tests.py
matrix:
  allow_failures:
    - rust: nightly
