language: rust
rust:
  - stable
  - beta
  - nightly
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - python3.4
before_script:
  - python3 -m compileall -b pythonlib examples
script:
  - cargo test
  - ./run_functional_tests.py
matrix:
  allow_failures:
    - rust: nightly
