[package]
name = "pythonvm"
version = "0.1.0"
authors = ["Valentin Lorentz <progval+git@progval.net>"]
build = "build.rs"

[lib]
name = "pythonvm"
path = "src/lib.rs"

[[bin]]
name = "pythonvm"
path = "src/bin.rs"

[dependencies]
